### ISSUE TITLE
big sur  작동 안하는 문제!

### ISSUE THREAD

**Issue by hjm79** [mollax/fanatstical_korean_alfred_workflow#1]
해당하는 폴더 
ruby parse.rb '8월15일 테 스트'

The file /Users/hjm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B07AC922-3EAE-4D56-9EC3-5900C29CAC8B/x-fantastical2:/parse?s=테스트 08.15.2021 does not exist.
x-fantastical2://parse?s=테스트 08.15.2021

맨 마지막 문구만 나와야 하는데 위에 에러가 나면서 작동을 안하는데 해결 방법이 있을까요!!!  빅서에서는  모든 사용자가 안되는듯 합니다.
r

**Comment by mollax** [comment]
제가 쓰던 앱들이 Big Sur에서 제대로 안 돌거나 새로 구매해야 하는 것들이 많아 업글을 안 하고 있었더니 이런 문제를 모르고 있었네요.

남의 노트북을 빌려 테스트를 해 보니, 기존에는 단순 문자열을 받아주었는데, BigSur에서는 URI 형식으로만 입력을 받는 것 같습니다.
URI 형식으로 전달하도록 수정해 동작하는 것을 확인했습니다.
새로 받아 보세요.

**Comment by hjm79** [comment]
감사합니다. 잘 되네요!    이것땜에 얼마나 고생했는지  ㅜ,.ㅜ
